### ISSUE TITLE
Changing sky color 

### ISSUE THREAD

**Issue by Digus12** [Postrediori/OceanSimulation#8]
Hello,

I was wondering how i can change the colors on both the sky and fog? Its something i want to do for an art project

**Comment by Postrediori** [comment]
Hi!
Colours are set up in files with fragment shaders (with the `*.frag` extension) in the `src/Ocean/data/` directory:
* https://github.com/Postrediori/OceanSimulation/blob/master/src/Ocean/data/ocean110.frag
* https://github.com/Postrediori/OceanSimulation/blob/master/src/Ocean/data/ocean130.frag
* https://github.com/Postrediori/OceanSimulation/blob/master/src/Ocean/data/ocean330.frag

The values for fog, sky and water are set up here as RGBA values between 0.0 and 1.0:
```
const vec4 fog_color      = vec4(0.25, 0.75, 0.65, 1.0);
const vec4 emissive_color = vec4(1.0, 1.0, 1.0,  1.0);
const vec4 ambient_color  = vec4(0.0, 0.65, 0.75, 1.0);
const vec4 diffuse_color  = vec4(0.5, 0.65, 0.75, 1.0);
const vec4 specular_color = vec4(1.0, 0.25, 0.0, 1.0);
```

These are almost identical files for different OpenGL versions. If not sure what version to use, modify all three.

**Comment by Postrediori** [comment]
I'm sorry to bit a year late, but in case you find this useful, there are now color changing controls in branch [adjust_colors](https://github.com/Postrediori/OceanSimulation/tree/adjust_colors):

![](https://user-images.githubusercontent.com/856993/85751490-4e0da480-b713-11ea-92c7-7c588fb9ac20.png)

**Comment by Postrediori** [comment]
Added color UI in #9
